/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import logica.*;

/**
 *
 * @author Jesús Pérez
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panNorte = new javax.swing.JPanel();
        lblMensaje = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        panMedio = new javax.swing.JPanel();
        lblResultado = new javax.swing.JLabel();
        panSur = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio 1: Par o Impar (con excepciones)");
        getContentPane().setLayout(new java.awt.GridLayout(3, 0));

        lblMensaje.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblMensaje.setText("Introduzca un número: ");
        panNorte.add(lblMensaje);

        txtNumero.setColumns(8);
        txtNumero.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        panNorte.add(txtNumero);

        getContentPane().add(panNorte);

        lblResultado.setBackground(new java.awt.Color(0, 0, 0));
        lblResultado.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        lblResultado.setForeground(new java.awt.Color(153, 0, 0));
        lblResultado.setText("Resultado...");
        panMedio.add(lblResultado);

        getContentPane().add(panMedio);

        btn1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        btn1.setText("¿Par o Impar?");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        panSur.add(btn1);

        getContentPane().add(panSur);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        resultado();
    }//GEN-LAST:event_btn1ActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        resultado();
    }//GEN-LAST:event_txtNumeroActionPerformed

    //----------------------- Métodos privados ----------------------------
    private void resultado(){
        String dato;
        dato=Lectura.validaEntero(txtNumero.getText());
        
        if (dato.equals("ERROR")) {
            lblResultado.setText(dato);
        } else {
           if (Ejer1.esPar(txtNumero.getText())) {
              lblResultado.setText("PAR");
           } else{
              lblResultado.setText("IMPAR");
        }  
        }    
    }//resultado()
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JPanel panMedio;
    private javax.swing.JPanel panNorte;
    private javax.swing.JPanel panSur;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
