/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.io.FileNotFoundException;
import java.io.IOException;
import javax.swing.JOptionPane;
import logica.*;

/**
 *
 * @author Jesús Pérez
 */
public class Ventana9 extends javax.swing.JFrame {

    /**
     * Creates new form Ventana9
     */
    public Ventana9() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panNorte = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panCentro = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pwdContraseña = new javax.swing.JPasswordField();
        panSur = new javax.swing.JPanel();
        btnIniciar = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio 9: Inicio de sesión");
        setSize(new java.awt.Dimension(400, 200));

        panNorte.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(102, 102, 102));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Introduzca su usuario y contraseña para iniciar sesión:");
        lblTitulo.setOpaque(true);
        panNorte.add(lblTitulo);

        getContentPane().add(panNorte, java.awt.BorderLayout.PAGE_START);

        lblUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        lblUsuario.setText("Usuario");

        lblContraseña.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        lblContraseña.setText("Contraseña");

        txtUsuario.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        pwdContraseña.setFont(new java.awt.Font("Liberation Sans", 0, 22)); // NOI18N
        pwdContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdContraseñaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panCentroLayout = new javax.swing.GroupLayout(panCentro);
        panCentro.setLayout(panCentroLayout);
        panCentroLayout.setHorizontalGroup(
            panCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCentroLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(panCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContraseña)
                    .addComponent(lblUsuario))
                .addGap(48, 48, 48)
                .addGroup(panCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuario)
                    .addComponent(pwdContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                .addContainerGap(265, Short.MAX_VALUE))
        );
        panCentroLayout.setVerticalGroup(
            panCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panCentroLayout.createSequentialGroup()
                .addGroup(panCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblUsuario)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(panCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblContraseña)
                    .addComponent(pwdContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 117, Short.MAX_VALUE))
        );

        getContentPane().add(panCentro, java.awt.BorderLayout.CENTER);

        panSur.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 50, 20));

        btnIniciar.setBackground(new java.awt.Color(0, 102, 255));
        btnIniciar.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("  Iniciar ");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        panSur.add(btnIniciar);

        btnAñadir.setBackground(new java.awt.Color(153, 0, 153));
        btnAñadir.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        panSur.add(btnAñadir);

        btnCancelar.setFont(new java.awt.Font("Liberation Sans", 0, 20)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        panSur.add(btnCancelar);

        getContentPane().add(panSur, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        loguear();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void pwdContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdContraseñaActionPerformed
        loguear();
    }//GEN-LAST:event_pwdContraseñaActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        try {
            if (Usuarios.añadirUsuario(txtUsuario.getText(), String.valueOf(pwdContraseña.getPassword()))){
                JOptionPane.showMessageDialog(this, "Usuario añadido correctamente");
            } else {
                JOptionPane.showMessageDialog(this, "El usuario ya existe");
            }
        } catch (IOException e) {
            System.out.println("Error de escritura "+e);
        } catch (Exception e) {
            System.out.println("Error genérico "+e);
        }
        
        
    }//GEN-LAST:event_btnAñadirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panCentro;
    private javax.swing.JPanel panNorte;
    private javax.swing.JPanel panSur;
    private javax.swing.JPasswordField pwdContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    //Métodos propios
    private void loguear(){
        boolean encontrado;
        
        try {
            encontrado=Usuarios.comprobarUsuario(txtUsuario.getText(), String.valueOf(pwdContraseña.getPassword()));
        
            if (encontrado) {
                JOptionPane.showMessageDialog(this, "¡¡Correcto!!");
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");
            }
        } catch (FileNotFoundException e) {
            System.out.println(e);
        } 
         catch (Exception e) {
            System.out.println("Error genérico "+e);
        }
        
        
    }//loguear()
}
