/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import logica.*;
import herramientas.Lectura;

/**
 *
 * @author Jesús Pérez
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn1 = new javax.swing.ButtonGroup();
        panGeneral = new javax.swing.JPanel();
        lbln = new javax.swing.JLabel();
        lblm = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        txtm = new javax.swing.JTextField();
        btnSuma = new javax.swing.JButton();
        btnResta = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnDivision = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ej.2: Calculadora de Números Reales (con excepciones)");

        panGeneral.setBorder(new javax.swing.border.MatteBorder(null));

        lbln.setText("n");

        lblm.setText("m");

        txtn.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N

        txtm.setFont(new java.awt.Font("Liberation Sans", 0, 36)); // NOI18N

        btnSuma.setText("n+m");
        btnSuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumaActionPerformed(evt);
            }
        });

        btnResta.setText("n-m");
        btnResta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaActionPerformed(evt);
            }
        });

        btnProducto.setText("m*m");
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnDivision.setText("n/m");
        btnDivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivisionActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Liberation Sans", 0, 48)); // NOI18N
        lblTotal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout panGeneralLayout = new javax.swing.GroupLayout(panGeneral);
        panGeneral.setLayout(panGeneralLayout);
        panGeneralLayout.setHorizontalGroup(
            panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGeneralLayout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGeneralLayout.createSequentialGroup()
                        .addComponent(lbln)
                        .addGap(18, 18, 18)
                        .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblm)
                        .addGap(28, 28, 28)
                        .addComponent(txtm, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGeneralLayout.createSequentialGroup()
                        .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panGeneralLayout.createSequentialGroup()
                                .addComponent(btnSuma)
                                .addGap(26, 26, 26)
                                .addComponent(btnResta)
                                .addGap(31, 31, 31)
                                .addComponent(btnProducto))
                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addComponent(btnDivision)))
                .addContainerGap())
        );
        panGeneralLayout.setVerticalGroup(
            panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGeneralLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbln)
                    .addComponent(lblm)
                    .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuma)
                    .addComponent(btnResta)
                    .addComponent(btnProducto)
                    .addComponent(btnDivision))
                .addGap(53, 53, 53)
                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumaActionPerformed
        String lectura1, lectura2;
        lectura1=Lectura.validaDouble(txtn.getText());
        lectura2=Lectura.validaDouble(txtm.getText());
        
        if (lectura1.equals("ERROR")||lectura2.equals("ERROR")) {
            lblTotal.setText("ERROR");
        } else {
            lblTotal.setText(Ejerc2.suma(lectura1,lectura2));
        }
    //suma()    
    }//GEN-LAST:event_btnSumaActionPerformed

    private void btnRestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaActionPerformed
        String lectura1, lectura2;
        lectura1=Lectura.validaDouble(txtn.getText());
        lectura2=Lectura.validaDouble(txtm.getText());
        
        if (lectura1.equals("ERROR")||lectura2.equals("ERROR")) {
            lblTotal.setText("ERROR");
        } else {
            lblTotal.setText(Ejerc2.resta(txtn.getText(),txtm.getText()));
        }
    //resta()
    }//GEN-LAST:event_btnRestaActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        String lectura1, lectura2;
        lectura1=Lectura.validaDouble(txtn.getText());
        lectura2=Lectura.validaDouble(txtm.getText());
        
        if (lectura1.equals("ERROR")||lectura2.equals("ERROR")) {
            lblTotal.setText("ERROR");
        } else {
            lblTotal.setText(Ejerc2.producto(txtn.getText(),txtm.getText()));
        }
    //producto()
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnDivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivisionActionPerformed
        String lectura1, lectura2;
        lectura1=Lectura.validaDouble(txtn.getText());
        lectura2=Lectura.validaDouble(txtm.getText());
        
        if (lectura1.equals("ERROR")||lectura2.equals("ERROR")) {
            lblTotal.setText("ERROR");
        } else {
            lblTotal.setText(Ejerc2.division(txtn.getText(),txtm.getText()));
        }
    //division()
    }//GEN-LAST:event_btnDivisionActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btn1;
    private javax.swing.JButton btnDivision;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnResta;
    private javax.swing.JButton btnSuma;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblm;
    private javax.swing.JLabel lbln;
    private javax.swing.JPanel panGeneral;
    private javax.swing.JTextField txtm;
    private javax.swing.JTextField txtn;
    // End of variables declaration//GEN-END:variables
}
