/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import logica.Ejerc3v1;
import herramientas.Lectura;

/**
 *
 * @author Jesús Pérez
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btg1 = new javax.swing.ButtonGroup();
        panGeneral = new javax.swing.JPanel();
        lbln = new javax.swing.JLabel();
        lblm = new javax.swing.JLabel();
        txtn = new javax.swing.JTextField();
        txtm = new javax.swing.JTextField();
        jrbSumatorio = new javax.swing.JRadioButton();
        jrbProductorio = new javax.swing.JRadioButton();
        Exponencial = new javax.swing.JRadioButton();
        btnCalcula = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio 3: Calculadora II");
        setResizable(false);

        lbln.setText("n");

        lblm.setText("m");

        btg1.add(jrbSumatorio);
        jrbSumatorio.setSelected(true);
        jrbSumatorio.setText("Sumatorio");
        jrbSumatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbSumatorioActionPerformed(evt);
            }
        });

        btg1.add(jrbProductorio);
        jrbProductorio.setText("Productorio");

        btg1.add(Exponencial);
        Exponencial.setText("Exponencial");
        Exponencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExponencialActionPerformed(evt);
            }
        });

        btnCalcula.setText("¡¡Calcula!!");
        btnCalcula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculaActionPerformed(evt);
            }
        });

        txtResultado.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panGeneralLayout = new javax.swing.GroupLayout(panGeneral);
        panGeneral.setLayout(panGeneralLayout);
        panGeneralLayout.setHorizontalGroup(
            panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGeneralLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(lbln)
                .addGap(18, 18, 18)
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbSumatorio)
                    .addComponent(Exponencial)
                    .addGroup(panGeneralLayout.createSequentialGroup()
                        .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(lblm)
                        .addGap(26, 26, 26)
                        .addComponent(txtm, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panGeneralLayout.createSequentialGroup()
                        .addComponent(jrbProductorio)
                        .addGap(38, 38, 38)
                        .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCalcula)
                .addGap(144, 144, 144))
        );
        panGeneralLayout.setVerticalGroup(
            panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panGeneralLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbln)
                    .addComponent(lblm)
                    .addComponent(txtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jrbSumatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbProductorio)
                    .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Exponencial)
                .addGap(18, 18, 18)
                .addComponent(btnCalcula)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbSumatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbSumatorioActionPerformed
         //Ejerc3v1.sumatorio(txtn.getText(),txtm.getText());
    }//GEN-LAST:event_jrbSumatorioActionPerformed

    private void ExponencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExponencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExponencialActionPerformed

    private void btnCalculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculaActionPerformed
        String n = Lectura.validaEntero(txtn.getText());
        String m = Lectura.validaEntero(txtm.getText());
        
        if (n=="ERROR"||m=="ERROR") {
            txtResultado.setText("ERROR");
        } else {
            if (jrbSumatorio.isSelected()) {
                txtResultado.setText(Ejerc3v1.sumatorio(txtn.getText(),txtm.getText()));
            } else {
                if (jrbProductorio.isSelected()) {
                    txtResultado.setText(Ejerc3v1.productorio(txtn.getText(),txtm.getText()));
                } else {
                    txtResultado.setText(Ejerc3v1.exponencial(txtn.getText(),txtm.getText()));
                }
            }//else
        }
        
    }//GEN-LAST:event_btnCalculaActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtResultadoActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Exponencial;
    private javax.swing.ButtonGroup btg1;
    private javax.swing.JButton btnCalcula;
    private javax.swing.JRadioButton jrbProductorio;
    private javax.swing.JRadioButton jrbSumatorio;
    private javax.swing.JLabel lblm;
    private javax.swing.JLabel lbln;
    private javax.swing.JPanel panGeneral;
    private javax.swing.JTextField txtResultado;
    private javax.swing.JTextField txtm;
    private javax.swing.JTextField txtn;
    // End of variables declaration//GEN-END:variables
}
