/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;
import java.awt.Font;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import logica.*;

/**
 *
 * @author Jesús Pérez
 */
public class Editor extends javax.swing.JFrame {

    /**
     * Creates new form editor
     */
    public Editor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        panNorte = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jSlider1 = new javax.swing.JSlider();
        panCentro = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaCentro = new javax.swing.JTextArea();
        panSur = new javax.swing.JPanel();
        btnAbrir = new javax.swing.JButton();
        btnGuadar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ejercicio 10: Mini editor de texto");

        lblTitulo.setBackground(new java.awt.Color(255, 51, 51));
        lblTitulo.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        lblTitulo.setText("Mini editor de texto");
        lblTitulo.setOpaque(true);
        panNorte.add(lblTitulo);

        jSlider1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSlider1StateChanged(evt);
            }
        });
        panNorte.add(jSlider1);

        getContentPane().add(panNorte, java.awt.BorderLayout.PAGE_START);

        txaCentro.setColumns(20);
        txaCentro.setRows(5);
        txaCentro.setBorder(javax.swing.BorderFactory.createTitledBorder("Aquí su texto..."));
        jScrollPane1.setViewportView(txaCentro);

        javax.swing.GroupLayout panCentroLayout = new javax.swing.GroupLayout(panCentro);
        panCentro.setLayout(panCentroLayout);
        panCentroLayout.setHorizontalGroup(
            panCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
            .addGroup(panCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE))
        );
        panCentroLayout.setVerticalGroup(
            panCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
            .addGroup(panCentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panCentroLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(panCentro, java.awt.BorderLayout.CENTER);

        panSur.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 60, 25));

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        panSur.add(btnAbrir);

        btnGuadar.setText("Guardar");
        btnGuadar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuadarActionPerformed(evt);
            }
        });
        panSur.add(btnGuadar);

        getContentPane().add(panSur, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        
        try {
            
            GestionarFichero.abrirFichero(jFileChooser1, txaCentro);
            
        } catch (FileNotFoundException e) {
            System.out.println(e);
        } catch (Exception e) {
            System.out.println(e);
        }
        
        
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnGuadarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuadarActionPerformed
        
        try {
            
            GestionarFichero.guardarFichero(jFileChooser1, txaCentro);
            
        } catch (FileNotFoundException e) {
            System.out.println(e);
        } catch (IOException e) {
            System.out.println(e);
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btnGuadarActionPerformed

    private void jSlider1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSlider1StateChanged
        int n;
        
        n=jSlider1.getValue();
        txaCentro.setFont(new Font(null,Font.PLAIN,n));
    }//GEN-LAST:event_jSlider1StateChanged

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnGuadar;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panCentro;
    private javax.swing.JPanel panNorte;
    private javax.swing.JPanel panSur;
    private javax.swing.JTextArea txaCentro;
    // End of variables declaration//GEN-END:variables
}
